baseURL: "https://ablanz.org/" 
title: Alkis Blanz
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3 
        - name: Newsletter
          url: https://pmichaillat.substack.com
          weight: 4

params:
    description: "I am a post-doctoral researcher at the Chair of Macroeconomics at the University of Leipzig. My research focuses on the intersection between climate change, macroeconomics and inequality.
consequat."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alkis Blanz   
          subtitle: "I am a post-doc at the chair of macroeconomics at the University of Leipzig. My research focuses on the Macroeconomics of Climate Change and Policy. "
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Prof. Name
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
       
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:alkis.blanz@uni-leipzig.de
        

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Prof. Name"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
